library("Seurat")
library("dplyr")
library("ggplot2")
library("sctransform")

data_dir <- '/Users/vanitharaguveer/Documents/RData/cellrangerFiltered/s285_filterMatrix'
list.files(data_dir)
bag.285.10x = Read10X(data.dir = data_dir)
class(bag.285.10x)
dim(bag.285.10x)
bag.285.10x[1:6, 1:6]
genes_1_transcript <- apply(bag.285.10x, 2, function(x) sum(x>0))
hist(genes_1_transcript, breaks=100, main="Distribution of Genes", xlab= "Genes with 1 tag")
summary(genes_1_transcript)
#hist(colSums(bag.284.10x), breaks =100, main="Expression per cell")
bag.285.S = CreateSeuratObject(bag.285.10x, min.cells=3, min.features = 150)
data.bag285 = GetAssayData(bag.285.S)
bag.285.S[["percent.mt"]] <- PercentageFeatureSet(bag.285.S, pattern = "MT-")
head(bag.285.S@meta.data)
VlnPlot(bag.285.S, features = c("nCount_RNA", "nFeature_RNA", "percent.mt"), ncol = 3)
plot1 <- FeatureScatter(bag.285.S, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot2 <- FeatureScatter(bag.285.S, feature1 = "nFeature_RNA", feature2= "percent.mt")
CombinePlots(plots=list(plot1, plot2))
table(bag.285.S@meta.data$percent.mt <15 &bag.285.S@meta.data$nFeature_RNA<3500)
bag.285.F <- subset(bag.285.S, subset = nFeature_RNA<3500 & percent.mt < 15)
data.bag285= GetAssayData(bag.285.F)
sbag <- SCTransform(bag.285.F, vars.to.regress = "percent.mt", verbose = FALSE)
sbag <- RunPCA(sbag, verbose=FALSE)
sbag1 <- RunTSNE(sbag, reduction = "pca", dims = 1:30, verbose = FALSE)
sbag <- RunUMAP(sbag,reduction="pca", dims=1:30, verbose=FALSE)
sbag <- FindNeighbors(sbag, dims=1:30, verbose = FALSE)
sbag <- FindClusters(sbag, verbose=FALSE)
sbag1 <- FindNeighbors(sbag1, dims=1:30, verbose = FALSE)
sbag1 <- FindClusters(sbag1, verbose=FALSE)
DimPlot(sbag, label = TRUE) + NoLegend()
DimPlot(sbag1, label = TRUE) + NoLegend()
#CD8 T cell populations (naive, memory, effector): CD8A, GZMK, CCL5, GZMK
#CD4 T cell populations (naive, memory, IFN-activated): S100A4, CCR7, IL32, ISG15
#B cell cluster: TCL1A, FCER2
#NK cells into CD56dim vs. bright clusters: XCL1 and FCGR3A
top10 <- head(VariableFeatures(sbag), 10)
plota <- VariableFeaturePlot(sbag)
plota1 <- LabelPoints(plota, points=top10, repel=TRUE)
LabelPoints(plota, points=top10, repel=TRUE)
top10 <- head(VariableFeatures(sbag1), 10)
plotb <- VariableFeaturePlot(sbag1)
plotb1 <- LabelPoints(plotb, points=top10, repel=TRUE)
LabelPoints(plotb, points=top10, repel=TRUE)
VlnPlot(object = sbag, features = c("CD8A", "GZMK", "CCL5"), pt.size = 0.2, ncol = 1)
VlnPlot(object = sbag, features = c("CD8A"), pt.size = 0.2, ncol = 1)
VlnPlot(object = sbag, features = c("IL7R"), pt.size = 0.2, ncol = 1)
VlnPlot(object = sbag, features = c("PPBP"), pt.size = 0.2, ncol = 1)
VlnPlot(object = sbag, features = c("MS4A1"), pt.size = 0.2, ncol = 1)
FeaturePlot(object = sbag, features = c("CD8A", "GZMK", "CCL5"), pt.size = 0.2, ncol = 3)
sbag.markers <- FindAllMarkers(sbag, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
sbag.markers %>% group_by(cluster) %>% top_n(n = 2, wt = avg_logFC)
top10 <- sbag.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_logFC)
top50 <- top10[1:50, ]
DoHeatmap(sbag, features = top50$gene) + NoLegend()
