library(Seurat)
library(cowplot)
ctrl.data <- Read10X(data.dir = "/Users/vanitharaguveer/Documents/RData/cellrangerFiltered/s284_filterMatrix")
acti.data <- Read10X(data.dir = "/Users/vanitharaguveer/Documents/RData/cellrangerFiltered/s285_filterMatrix")

ctrl <- CreateSeuratObject(counts = ctrl.data, project = "Immune_ctrl", min.cells = 5)
ctrl$stim <- "CTRL"
ctrl <- subset(ctrl, subset = nFeature_RNA>500 & nFeature_RNA<3500)
ctrl <- PercentageFeatureSet(ctrl, pattern = "^MT-", col.name = "percent.mt")
ctrl <- SCTransform(ctrl, vars.to.regress = "percent.mt", verbose = FALSE)

stim <- CreateSeuratObject(counts = acti.data, project = "Immune_stim", min.cells = 5)
stim$stim <- "STIM"
stim <- subset(stim, subset = nFeature_RNA>500 & nFeature_RNA<3500)
stim <- PercentageFeatureSet(stim, pattern = "^MT-", col.name = "percent.mt")
stim <- SCTransform(stim, vars.to.regress = "percent.mt", verbose = FALSE)

immune.anchors <- FindIntegrationAnchors(object.list = list(ctrl,stim), dims=1:20)
immune.combined <- IntegrateData(anchorset = immune.anchors, dims = 1:20)

DefaultAssay(immune.combined) <- "integrated"
immune.combined <- ScaleData(immune.combined, verbose=FALSE)
immune.combined <- RunPCA(immune.combined, npcs = 30, verbose = FALSE)
immune.combined <- RunUMAP(immune.combined, reduction = 'pca', dims = 1:20)
immune.combined1 <- RunTSNE(immune.combined, reduction = 'pca', dims = 1:20)
immune.combined <- FindNeighbors(immune.combined, reduction = 'pca', dims=1:20)
immune.combined <- FindClusters(immune.combined, resolution = .5)
immune.combined1 <- FindNeighbors(immune.combined1, reduction = 'pca', dims=1:20)
immune.combined1 <- FindClusters(immune.combined1, resolution = .5)
p1 <- DimPlot(immune.combined, reduction = 'umap', group.by = 'stim')
p2 <- DimPlot(immune.combined, reduction = 'umap', label = TRUE)
p3 <- DimPlot(immune.combined1, reduction = 'tsne', group.by = 'stim')
p4 <- DimPlot(immune.combined1, reduction = 'tsne', label = TRUE)
plot(p1)
plot(p2)
plot(p3)
plot(p4)
DimPlot(immune.combined1, reduction = 'tsne', split.by = "stim")
DimPlot(immune.combined, reduction = 'umap', split.by = 'stim')

DefaultAssay(immune.combined) <- "RNA"
markers1 <- FindConservedMarkers(immune.combined, ident.1 = 1, grouping.var = "stim", verbose = FALSE)
head(markers1)
markers2 <- FindConservedMarkers(immune.combined, ident.1 = 2, grouping.var = "stim", verbose = FALSE)
markers3 <- FindConservedMarkers(immune.combined, ident.1 = 3, grouping.var = "stim", verbose = FALSE)
markers4 <- FindConservedMarkers(immune.combined, ident.1 = 4, grouping.var = "stim", verbose = FALSE)
markers5 <- FindConservedMarkers(immune.combined, ident.1 = 5, grouping.var = "stim", verbose = FALSE)
markers6 <- FindConservedMarkers(immune.combined, ident.1 = 6, grouping.var = "stim", verbose = FALSE)
markers7 <- FindConservedMarkers(immune.combined, ident.1 = 7, grouping.var = "stim", verbose = FALSE)
markers8 <- FindConservedMarkers(immune.combined, ident.1 = 8, grouping.var = "stim", verbose = FALSE)
markers9 <- FindConservedMarkers(immune.combined, ident.1 = 9, grouping.var = "stim", verbose = FALSE)
markers10 <- FindConservedMarkers(immune.combined, ident.1 = 10, grouping.var = "stim", verbose = FALSE)
markers11 <- FindConservedMarkers(immune.combined, ident.1 = 11, grouping.var = "stim", verbose = FALSE)
markers12 <- FindConservedMarkers(immune.combined, ident.1 = 12, grouping.var = "stim", verbose = FALSE)
